import {StyleSheet} from 'react-native';
import {colors} from '@src/theme';

const styles = StyleSheet.create({
  container: {paddingHorizontal: 16, backgroundColor: colors.lightGray, marginTop: Platform.OS === 'ios' ? 40 : 0},
  contentContainer: {rowGap: 12, paddingBottom: 120},
  headerLabel: {
    fontSize: 32,
    fontWeight: '700',
    color: colors.black,
    marginVertical: 12,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.semiLightGray,
    borderRadius: 8,
  },
  inputStyle: {padding: 8},
  listContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 150,
    borderRadius: 4,
    padding: 12,
    backgroundColor: colors.white,
    elevation: 5,
    columnGap: 24,
  },
  productName: {fontSize: 18, fontWeight: '700', color: colors.black},
  productDetail: {flex: 1, rowGap: 6},
  productCategory: {fontSize: 14, fontWeight: '700', color: colors.orange},
  productDesc: {fontSize: 12, fontWeight: '400'},
  productImg: {
    width: 100,
    height: 120,
    resizeMode: 'contain',
    borderRadius: 10,
  },
  addToCart: {height: 150, width: 100, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.orange, borderRadius: 8},
  cartBtnContainer: {height: 150, width: 100, alignItems: 'center', justifyContent: 'center', borderRadius: 8},
  cartPlusMinus: {flexDirection: 'row', flex: 1, alignItems: 'center'},
  removeButton: {
    height: 150 / 2,
    width: 100,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.red,
    borderBottomEndRadius: 8,
    borderBottomStartRadius: 8,
  },
  updateQty: {
    height: 150 / 2,
    width: 100 / 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addQty: {backgroundColor: colors.green, borderTopEndRadius: 8},
  minusQty: {backgroundColor: colors.amber, borderTopStartRadius: 8},
  addToCartText: {fontSize: 18, fontWeight: '700', color: colors.white},
  totalSummaryContainer: {
    position: 'absolute',
    height: 100,
    backgroundColor: colors.white,
    bottom: 0,
    right: 0,
    left: 0,
    borderWidth: 0.3,
    paddingHorizontal: 16,
    paddingVertical: 12,
    rowGap: 12,
  },
  flexDirection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
});

export default styles;
